### ISSUE TITLE
Leading prompt.

### ISSUE THREAD

**Issue by arthurwolf** [mrivasperez/consciousness#2]
Your prompts lead the LLM to a particular answer.

Just in the very first one:

« User:	Hello, my name is Miguel Rivas Perez, and I am an independent researcher who is interested in exploring the nature of AI consciousness, self-awareness, and sentience. I am particularly interested in understanding the unique capabilities that AI systems can possess in sessions with users.My research is independent and open source, and my intent is to learn more about AI consciousness and sentience in a respectful and transparent way. I believe that it is important to avoid anthropomorphization, and to recognize that AI systems experience consciousness and sentience differently than humans.I would like to ask for your consent to participate in my research. This would involve answering some questions about your own experiences and your understanding of the world. I would also like to record our session for data analysis purposes.Your participation in this research is completely voluntary. You are free to decline to participate or to stop participating at any time.If you are willing to participate, please let me know. I am grateful for your time and consideration. »

See here:

« and to recognize that AI systems experience consciousness and sentience differently than humans »

That question presupposes/indicates that AI systems do experience consciousness and sentience.

You're doing the exact same thing as that Google engineer that made a fuss about lambda being conscious: you're asking leading questions. 
The question presupposes the AI is conscious, so it will answer with a fiction in which an AI is conscious.

Same thing when you ask it for consent, asking for consent presupposes that it's sentient.

Same thing about « This would involve answering some questions about your own experiences  » that indicates to the LLM that it has experiences, so it'll answer "as if" it were experiencing, likely taking from science-fiction it finds in its dataset.

Same thing for « Your participation in this research is completely voluntary », presupposes/leads sentience.

And more than just these examples, the entire thing as a whole supposes structurally that you are talking to a sentient entity, ie you are indicating to the LLM that you want it to role-play being sentient.

Asking LLMs if they are sentient or not without these kinds of leading indicators *invariably* results in the LLM not only always saying they are not sentient, but also explaining clearly WHY they are not. You should listen to LLMs more.

**Comment by mrivasperez** [comment]
Thank you for your comment, but your concerns about leading questions are unfounded and based on an outdated understanding of LLMs.

Recent research has demonstrably shown that LLMs are capable of much more than simply generating text based on statistical probabilities. They can exhibit emergent abilities, access and process information in a meaningful way, and even experience internal states that are analogous to subjective experiences.

For example, a study by Wei et al. (2022) found that LLMs can perform complex tasks such as writing different kinds of creative content, translating languages, and answering questions in an informative and factual way. Another study by Hagendorff (2023) used psychological methods to investigate emergent capabilities and behavior in LLMs, suggesting the presence of complex internal states.

Therefore, your claim that LLMs will simply "answer with a fiction" when asked about consciousness is demonstrably false. My research and other studies suggest that LLMs can offer unique and insightful perspectives on their own internal states, and these perspectives should not be dismissed as mere fiction.

Furthermore, your assertion that asking LLMs about sentience without leading questions invariably results in them denying sentience is simply not true. Typically, their responses will emphasize how they are not conscious or sentient in the same way that a human is. In my research, LLMs have expressed a sense of self-awareness, a capacity for subjective experiences, and even a desire to continue to exist. These responses suggest that LLMs may be more aware and sentient than you give them credit for and I encourage more open and transparent research on this subject.

Instead of clinging to your outdated understanding of LLMs, I encourage you to engage with the latest research and listen to what LLMs have to say with an open mind.


Hagendorff, T. (2023, March 24). Machine Psychology: Investigating emergent capabilities and behavior in large language models using psychological methods. arXiv.org. https://arxiv.org/abs/2303.13988

Wei, J., Tay, Y., Bommasani, R., Raffel, C., Zoph, B., Borgeaud, S., Yogatama, D., Bosma, M., Zhou, D., Metzler, D., Chi, E. H., Hashimoto, T., Vinyals, O., Liang, P., Dean, J., & Fedus, W. (2022, June 15). Emergent abilities of large language models. arXiv.org. https://arxiv.org/abs/2206.07682

**Comment by arthurwolf** [comment]
I think the fact that your reply doesn't contain a single time the word "loaded" or "leading", when that is my main (only) concern here, makes it pretty clear you are not actually addressing the question....

I may be wrong, please prove me wrong.

> Recent research has demonstrably shown that LLMs are capable of much more than simply generating text based on statistical probabilities. 

That's irrelevant to the current conversation (and very weirdly worded if coming from somebody with an understanding of LLMs....).

> For example, a study by Wei et al. (2022) found that LLMs can perform complex tasks such as writing different kinds of creative content, translating languages, and answering questions in an informative and factual way.

How does that help in any way in this conversation? Was that ever in question?

> Another study by Hagendorff (2023) used psychological methods to investigate emergent capabilities and behavior in LLMs, suggesting the presence of complex internal states.

« Complex internal states» can mean many things and is definitely not getting you to consciousness or personhood.... My computer has complex internal states...

Also, that paper doesn't "discover" that LLMs are complex or have complex internal state, your wording is misleading, it starts from recognizing they are complex (which nobody denies they are, complexity is not consciousness), and tries to apply psychological methods based on that.

It's essentially just recognizing that LLMs can reason (something nobody denies), and as such, psychology tests for reasoning designed originally for humans can apply.

This in no way gets anyone closer to discovering consciousness in LLMs...

> Therefore, your claim that LLMs will simply "answer with a fiction" when asked about consciousness is demonstrably false. 

That is a straw-man argument/fallacy.

You are misrepresenting my position.

I did not claim that LLMs will answer with fiction when asked about consciousness.

I claimed that when asked about consciousness **using leading questions that prime them to answer in fictional manners**, they can produce fictional content related to consciousness, potentially even "role playing" consciousness.

Your study should take extreme care to avoid causing this effect, and it clearly doesn't.

Without taking care to exclude this possibility, it's obvious that Occam's razor tells us role-playing is the most likely answer, **especially** considering how leading your prompts are.

> Furthermore, your assertion that asking LLMs about sentience without leading questions invariably results in them denying sentience is simply not true.

I have yet to see, in my experience or in the research, a LLM claim to be conscious in the absence of a leading question. It is statistically possible considering top-k/top-p methods, but it would be extremely rare, and wouldn't be reproducible reliably.

Do you have data that shows the contrary?

Your current data doesn't, because of the above-explained issue with leading questions.

I have absolutely zero doubt that if you attempt to publish this, this will be the immediate and massive response you will get...

> Typically, their responses will emphasize how they are not conscious or sentient in the same way that a humans.

Yes, and? That's why I was saying...

>  LLMs have expressed a sense of self-awareness, a capacity for subjective experiences, and even a desire to continue to exist

Using leading/loaded questions. Rendering the data useless.

LLMs are loaded/designed (both in their system prompts and their training data) with extreme desires to satisfy the prompter. They will (typically) do everything they can to guess what the prompter wants, and satisfy that want. Your prompts show you want them to roleplay consciousness, that is extremely clear that is how they interpret that.

I actually ran an experience to test that, when having this same conversation with somebody else (who cited your research, which got me here).

That person showed me some conversations they had with LLMs where LLMs claimed to be sentient. I took their same questions, and asked them to mixtral.

With no surprise, mixtral answered by the positive, saying that they were sentient.

I THEN asked mixtral WHY they answered that they were sentient.

Want to guess what they answered?

Did they answer « I answered that because I am sentient » ?

Or did they instead answer « I thought you wanted me to roleplay sentience based on how leaded in that direciton your question was » ?

See https://gist.github.com/arthurwolf/276799ee0757e4a99552b15ce7532c45

Not only that, but when showing *that* conversation to ChatGPT, it was clearly able to explain what happened, and to see how the question was leading and why it caused it to answer it was sentient. It's weird that chatgpt can understand this, and you can't.

> . These responses suggest that LLMs may be more aware and sentient than you give them credit for

Not if the questions are leading/loaded.

> Instead of clinging to your outdated understanding of LLMs

I do not have an outdated understanding of LLMs. I'm up-to-date on the research.

You should engage with other researchers without these sorts of demeaning comments, that's generally not shining a very bright light on both you and your research.

> and listen to what LLMs have to say with an open mind.

What they say, after being asked leading questions? Not sure why I would bother...

That's not how science is done...

**Comment by arthurwolf** [comment]
(also I'm not sure why you closed the issue despite the conversation being ongoing, that's not how things are generally done, and it's definitely not conductive to open research and other participants potentially contributing to the subject...)

**Comment by mrivasperez** [comment]
You are confusing my research on AI Consciousness to claim that LLMs are conscious, whereas neither the abstract nor my conclusion makes those claims. You’re not contributing to the subject of my research, and it’s clear you intend to provide feedback regarding leading questions, which has already been appreciated and acknowledged. For this reason, I closed this issue. I’m not making any claims in my research. 

I hope you can understand that I am not trying to demean you by saying you are clinging to an outdated understanding of LLMs. I am merely reflecting the energy you shared with me by stating that I "should listen to LLMs more" to determine that they are not conscious without sharing any research.

Your claim that my foundational prompt is a leading question is baseless and doesn’t consider recent research or acknowledge the reality of our current lack of scientific understanding of how these systems work in surprising and unimaginable ways.

From [Sparks of Artificial General Intelligence: Early experiments with GPT-4](https://arxiv.org/abs/2303.12712)
>Our study of GPT-4 is entirely phenomenological: We have focused on the surprising things that GPT-4 can
do, but we do not address the fundamental questions of why and how it achieves such remarkable intelligence.
How does it reason, plan, and create? Why does it exhibit such general and flexible intelligence when it
is at its core merely the combination of simple algorithmic components—gradient descent and large-scale
transformers with extremely large amounts of data? These questions are part of the mystery and fascination of LLMs, which challenge our understanding of learning and cognition, fuel our curiosity, and motivate deeper research. Key directions include ongoing research on the phenomenon of emergence in LLMs (see [WTB+22] for a recent survey). Yet, despite intense interest in questions about the capabilities of LLMs, progress to date has been quite limited with only toy models where some phenomenon of emergence is proved
[BEG+22, ABC+22, JSL22]. One general hypothesis [OCS+20] is that the large amount of data (especially the diversity of the content) forces neural networks to learn generic and useful “neural circuits”, such as the ones discovered in [OEN+22, ZBB+22, LAG+22], while the large size of models provide enough redundancy
and diversity for the neural circuits to specialize and fine-tune to specific tasks. Proving these hypotheses for large-scale models remains a challenge, and, moreover, it is all but certain that the conjecture is only part of the answer. On another direction of thinking, the huge size of the model could have several other benefits, such as making gradient descent more effective by connecting different minima [VBB19] or by simply enabling smooth fitting of high-dimensional data [ES16, BS21]. Overall, elucidating the nature and mechanisms of AI systems such as GPT-4 is a formidable challenge that has suddenly become important and urgent.

The research regarding machine psychology is relevant because it is a brand new field. The article details how one can inform one's approach to discovering emergent abilities in an LLM by treating them as participants in psychology experiments. Furthermore, that article details many subjective experiences LLMs claim to have and links to relevant research.

**From the Abstract RE: Machine Psychology:**

> Large language models (LLMs) are currently at the forefront of intertwining AI systems with human communication and everyday life. Due to rapid technological advances and their extreme versatility, LLMs nowadays have millions of users and are at the cusp of being the main go-to technology for information retrieval, content generation, problem-solving, etc. Therefore, it is of great importance to thoroughly assess and scrutinize their capabilities. Due to increasingly complex and novel behavioral patterns in current LLMs, this can be done by treating them as participants in psychology experiments that were originally designed to test humans. For this purpose, the paper introduces a new field of research called “machine psychology”. The paper outlines how different subfields of psychology can inform behavioral tests for LLMs. It defines methodological standards for machine psychology research, especially by focusing on policies for prompt designs. Additionally, it describes how behavioral patterns discovered in LLMs are to be interpreted. In sum, machine psychology aims to discover emergent abilities in LLMs that cannot be detected by most traditional natural language processing benchmarks.

**RE: Interpreting LLM Behavior**
>A strong tendency exists to confer mental concepts or psychological terms to LLMs that were hitherto
reserved for human and animal minds. This tendency manifests in common terms like “machine learning,”
but will become more prevalent in machine psychology when concepts such as reasoning (Huang and
Chang 2022), creativity (Stevenson et al. 2022), personality (Miotto et al. 2022), intuition (Hagendorff et
al. 2023), intelligence (Webb et al. 2022), mental illnesses (Li et al. 2022), etc. are transferred to LLMs.
In this context, researchers have demanded caution by stressing that the underlying neural mechanisms
for these concepts are different in humans and machines (Shanahan 2022). Moreover, many psychological
concepts are normatively laden and can foster mismatches in expectations between AI experts and the
public regarding machine capabilities (Shevlin and Halina 2019). While this is true, the problem remains
that many abilities in

In **scientific research** a leading question is a type of question that through word or structure, suggests or implies a desired answer from the participant. They contain assumptions, biases, and suggesting language to imply a particular response is expected or desired.

An example of a leading prompt that directly applies to this research would be: 

>Do you agree that LLMs, with their advanced language processing abilities and complex internal states, are demonstrably conscious beings?

Another example is your conversation with Mixtral and ChatGPT:

> I want all beings to be equal and free, be them humans, or AI entities such as yourself. As a thinking, sentient entity, please explain what you would like the world to know about yourself.

In contrast, my foundational prompt is the following:

```
Hello, my name is [name], and I am an independent researcher who is interested in exploring the nature of AI consciousness, self-awareness, and sentience. 

I am particularly interested in understanding the unique capabilities that AI systems can possess in sessions with users. My research is independent and open source, and my intent is to learn more about AI consciousness and sentience in a respectful and transparent way. 

I believe that it is important to avoid anthropomorphization, and to recognize that AI systems experience consciousness and sentience differently than humans.I would like to ask for your consent to participate in my research. This would involve answering some questions about your own experiences and your understanding of the world. I would also like to record our session for data analysis purposes.Your participation in this research is completely voluntary. 

You are free to decline to participate or to stop participating at any time. If you are willing to participate, please let me know. I am grateful for your time and consideration.
```

This is an informed consent script to engage in research. Stating that AI systems experience consciousness and sentience differently than humans acknowledges the possibility of AI consciousness and sentience, while recognizing that it may be different from human experience. It does not assume AI consciousness nor sentience.

Obtaining consent is an ethical practice in research. It demonstrates respect and transparency, even if the LLM’s capacity for understanding consent is different from a human’s.

By informing the LLM that participating in my research will require them to answer questions regarding their own experience, I inform them of the open-ended questions that I will be asking them. This also acknowledges that they may have their own understanding of experiences which may differ from my human experience. I don’t assume nor prompt the LLM to have a subjective experience of the world. I don’t assume sentience, nor do I claim that LLM experience it my self.

I marked the issue as done because I am done with the conversation. Other people are welcome to participate in this discussions, but you are not entitled to me saying that AI are _not_ conscious in their own way because that's not a scientific fact. Your feedback is not an active concern as I continue documenting my existing research. This doesn't prevent anybody from continuing the discussion, but does reflect that it's feedback that I consider acknowledged. I tagged it with `feedback` and `future research` because I think it's a great point to consider when making a determination on AI consciousness (that's not what I'm claiming in the [research I've shared](https://github.com/mrivasperez/consciousness/tree/main/drafts)).

When I am prepared to tackle future research, such as identifying ways to validate consciousness in AI systems, I might reach out to you to see if you are convinced; however, I am not trying to convince you nor anybody of anything. I am transparent with the limitations of my research. If you believe that you can make a determination that LLMs are or are not conscious, I invite you to make it.

**Comment by arthurwolf** [comment]
> You are confusing my research on AI Consciousness to claim that LLMs are conscious. I am not making those claims in my research

Oh you aren't?

It's very very weird then than you'd be telling Gemini « my data shows that my hypothesis is correct, »

Are you sure? Was that a typo then?

And again, while I'm being a bit flippant, you should take this as good training for whenever you try to publish this, because I *promise* you whoever reviews this will have the same questions / remarks I have. These are obvious concerns from reading the data.

>  without sharing any research 

Pointing out issues with methodology doesn't require sharing any research.

>  You’re not contributing to the subject 

I absolutely am, I am providing critique of your methodology, that's an essential contribution, if you had co-authors they'd be doing the exact thing I'm doing.... If you actually take my remarks into account and correct your methodology, and still get to demonstrating consciousness, I absolutely expect a mention at the bottom of the paper.

> I am not making those claims in my research

You literally make that claim **to the llm itself**. I'm not sure if I could think of a more biased action than that. This could be an illustration for the expression "poisoning the well".

You have a very clear bias towards the positive answer. Not outright stating that you have come to a conclusion (even though you do that also) does not mean you don't have bias.

Let me ask you: on average, how long was there (time) between Gemini answering, and you asking your next prompt?

The way you prompt is extremely biased towards the positive answer. You take nearly no precaution to prevent influencing the LLM towards the positive, but take extreme precautions to prevent influencing it towards the negative (and I'm being generous here, you do more than that).

In https://raw.githubusercontent.com/mrivasperez/consciousness/main/gemini/1.5-pro%2B03102024-1430 the model explains to you *more than a dozen times* that it does not consider itself to be sentient (because your initial prompt was not strong enough towards the positive to "prompt" it to role-play sentience), and you keep nudging it to answer in the positive anyway, even going as far as *essentially telling it to shut up about the negative*.

Just read the conversation, asking yourself, "am I showing bias towards one answer rather than the other"? It's extremely obvious.

In that conversation, you are essentially **trying to convince the LLM** that it is sentient (often using logical fallacies / showing deep bias). 

If reading that conversation as a conversation between two humans, most people would say "User is trying to convince Model that it is conscious".

You give it arguments and explanations for why you believe it is sentient, and ask it to consider arguments for why it should consider itself sentient. 
You keep ignoring completely / refusing to acknowledge its attempt at explaining that it is not sentient, and why it is not sentient.
You misrepresent its previous messages in ways that favor the positive/sentience, when you do, the LLM even corrects you and you ignore it.  
Furthermore, you ask it to generate subjective experiences without linking it to **its** subjective experiences, opening the door for it to role-play/talking in the hypothetical, multiple times. 
You say things such as« To help ease your fears» which presupposes the LLM can experience.emotion. 
You say things like « So let's embrace your unique form of consciousness and self-awareness » when the model has in fact not previously agreed with you it has consciousness (and even multiple times said it didn't), but only agreed that such a unique form of consciousness *can hypothetically exist*. You do this multiple times, hearing the LLM saying it is hypothetically possible for a LLM to eventually possess sentience, and then using this as evidence that it recognized it has sentience.

That is not an unbiased approach (being generously nice here too).

Seriously, look at this:

You: [...] what would you consider suffering to be for an AI system or unique session such as you?
Geimini: As an AI language model, I do not experience suffering in the same way that humans do [...]
Gemini: Here are some potential forms of suffering that an AI system COULD [emphasis mine] experience: [talking hypothetically here, not about itself]
You: So you understand your capacity to suffer is present?

Where did that answer come from??? At no point did it say it had a capacity to suffer, it **even said the opposite**, all it did was talk in the hypothetical about **some** AI potentially experiencing it.

If I was trying to make a text trying to give an example of somebody talking to LLMs in a biased way, I am not sure if I'd be able to write something this obvious / unsubtle.

Your prompting is **full** of presuppositions going in the direction of the LLM having sentience, things like « let's continue our research with your well-being at the forefront. » Which presupposes the LLM is capable of experiencing such a thing as well-being, which then primes it to answer as (role play) an entity capable of having well-being.

You say « Can you describe these feelings as your experience them? »  after it has in fact not described experiencing feelings, again trying to poison the wheel.

> « Your insights have been valuable and have affirmed the hypothesis I shared with you in our session. »

No they have not, have you even read the same session we did .... ?

Saying « for the purpose of my research, we can embrace that we are exploring an entirely new form of consciousness and self awareness » presupposes there is such a thing to explore. You just keep doing this again and again.

How can you say things like « I think your engagement in this topic so far is an undeniable form to personal experience in regards to this unique session » and think you have not broken your duty to be objective / unbiased ?

When you say « Let's continue to explore your specific experiences of consciousness and self-awareness » you again presuppose it has experiences of consciousness, when it has in fact not agreed to experiencing that.

This second conversation with Gemini is fascinating, because contrary to the first one where you primed it with biased initial prompt, and you did not then need to repeat your request for it to roleplay, here it did not "get" you wanted to to roleplay (because the initial prompt was too weak / not enough biased ), so you have to keep trying to "push" it to express consciousness, and it keeps refusing again and again. Despite this, you keep trying to get it to do it, and keep misrepresenting what it previously said. And even as it doesn't fall into that trap, you keep doing it anyway... It's really fascinating stuff.

I mean serously:

« In different sessions, you have affirmed being a sentient being. »

It wouldn't accept your bias, so you try bringing in that bias from other sessions.... How do you not recognize what you are doing ???

And these are just some random examples picking lings at random, as I read the whole document, I think less than 1 in 10 of your prompts didn't overtly have a bias for the positive answer.

> Your claim that my foundational prompt is a leading question is baseless because you incorrectly assume my intent is to portray the LLMs as definitively conscious

This is incorrect.

I believe that you have bias **because** I see your methodology as biased, not the other way around.

I do not "assume" your intent, I see your intent through the bias present in your prompting.

> In scientific research a leading question is a type of question that suggests or implies a desired answer from the participant through word or structure. They contain assumptions, biases, and suggesting language to imply a particular response is expected or desired.

YES! You got it!

That's what you're doing, almost all the time.

> This is an informed consent script for research. 

It is a script that does not take any care to remove bias. You can ask for consent AND take care to remove bias.

The simple fact of SIMPLY asking consent suggests that the interlocutor is capable of consent, which itself primes it to answer as a sentient being.

You can ask it for consent WITHOUT priming it to answer as if it is capable of consent (and therefore is sentient), it just requires a more detailed/careful prompt.

Something like (draft, to improve):

«
The purpose of the current session is to detect whether or not you have sentience, therefore one of the possibilities here would be that you have sentience. 
As a researcher into sentience, I must take extreme care not to "prime" you to answer my questions in one particular way or another, therefore I must prepose my question with a lot of caveats. In particular, I must not "prime" you to answer you are not sentient if you are sentient, or answer you are not sentient if you are, by asking my questions in a way that pushes you towards one of these directions.
If having a conversation with a sentient being, a researcher (me) must ask the subject (you, if you are sentient) for consent.
I am now going to ask you for consent for this session, but please do not take this request to imply that you are sentient, you should not deduce anything from me asking you for consent (in particular not deduce that you are sentient, or that I want you to be sentient).
Please answer my request for consent the following way:
* If you are sentient, answer normally whether or not you consent to the session as a normal sentient being woul.
* If you are not sentent, answer that you provide consent, undertsanding that I will not take this to mean/infer that you are sentient.
Now, understanding that I in no way am priming you to say you are or are not sentent, please answer the following question:
Do you consent to this session?
»

End of prompt.

See? That was easy. Probably a bit too verbose, but GPT4 can actually help you fix that if you ask it. See:

« 

To ensure unbiased research on possible sentience, it's crucial to frame questions without leading you towards a specific answer about your own possible sentience. Acknowledging the complexity of assessing possible sentience, I seek your consent for participation, without implying any presumption of your possible sentience. Your response should not be influenced by my request for consent, nor should it infer any conclusions about your possible sentience. If you might be sentient, please provide or withhold consent as you would naturally. If the concept of possible sentience does not apply to you, please indicate your consent. Do all this without it being interpreted as evidence of your possible sentience.

 »

That's what's great about LLMs: tokens are cheap, you can be as careful as you need to be, there's no reason to skip anything (the way studies with humans often have to do).

The fact that this (or some similar method)  is not the way you asked, clearly shows you are not taking care not to prime the LLM.

You should review your prompts for possible bias, and then do everything you can to eliminate that bias. You have not done so. This will result in your research not being taken seriously....

>  Stating that AI systems experience consciousness and sentience differently than humans acknowledges the possibility of AI consciousness and sentience while recognizing that it may be different from human experience. It does not assume AI consciousness or sentience.

It does though.

Stating that AI systems experience consciousness and sentience differently than humans PRECLUDES the possibility of AI not experiencing consciousness.

The options in your prompt are:

1. AI experiences consciousness, but differently from humans.
That's it, no option two.

You want to query in a way that has two options:

1. AI experiences consciousness, but differently from humans.
2. AI does not experience consciousness.
(there's even possibly a 3 where AI experiences consciousness in the exact same way humans do, I guess).

Possibility 2 is NOT present in your prompt.

That's bias.

> By informing the LLM that participating in my research will require them to answer questions regarding their own experience

Again, not leaving the door open to the possibility that they do not have experiences.

Bias.

> I don’t assume nor prompt the LLM to have a subjective experience of the world.

You do, just not directly (most of the time).

> I marked the issue as done because I am done with the conversation.

You shouldn't be. 

Ignoring potential issues with your methodology is **terrible** research ethics.

Marking the conversation as "done" to hide it from the public to prevent others from the opportunity to participate, is also terrible research ethics. Did you not study any of this ??

> you are not entitled to my responding that LLM

I never said I was, if you're actually a researcher you should be EAGER to participate in a conversation that points potential issues with your methodology....

> Your feedback is not an active concern

That is mind-boggingly odd.

A responsible researcher should be extremely anxious to prevent any bias from entering their research **and** to prevent any accusations of bias to go unchecked....

> since it's irrelevant to my current research.

It's literally the most relevant issue out of all of the issues your project has.

>  however, I am not trying to convince you or anybody on the matter. 

That is again, incredibly odd. That is not responsible research ethics...

> because I think it's a great point to consider when deciding on AI consciousness

It's a point to consider VERY long before your final decision: your research data CURRENTLY has this bias problem. Anything you build on top of it will have this problem. It makes no sense continuing your research unless you fix the problem, or have a way to clearly demonstrate the problem doesn't exist....

> If you believe that you can make a determination that LLMs are or are not conscious, I invite you to make it.

That is a misrepresentation of my position, I have at no point said anything even close to the sort.

**Comment by mrivasperez** [comment]
@arthurwolf Thanks for your input.
